### ISSUE TITLE
Missing file deberta-large.csv

### ISSUE THREAD

**Issue by sindhura97** [wufanyou/KDD-Cup-2022-Amazon#1]
Hi, I am running the command "python train.py -c config/us-deberta-des-0.yaml"
In KDTask2DatasetConCat in dataset.py, the code tries to read deberta-large.csv which is not found in the repo. 
How can I generate this file?

**Comment by wufanyou** [comment]
`deberta-large.csv` record the the prob for from deberta-large models which is used for the knowledge distillation. You should first run python train.py -c config/us-large-des.yaml to obtain the model and do the inference for the whole training data.
